security:
    # 1. Configuración de encriptado
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # 2. Dónde están los usuarios (Base de datos)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # 3. Jerarquía de roles
    role_hierarchy:
        ROLE_ADMIN: ['ROLE_USER']
        ROLE_TRABAJADOR: ['ROLE_USER']

    # 4. Cortafuegos (Reglas de entrada)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # A. Zona de Login (Aquí se consigue el Token)
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: email
                password_path: password

        # B. Zona API (Aquí se usa el Token)
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    # 5. Control de Acceso (Quién puede ver qué)
    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS } # Login público
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }  # Documentación pública
        - { path: ^/api/users, roles: PUBLIC_ACCESS, methods: [POST] } # Registro público
        - { path: ^/api/trabajadors, methods: [GET], roles: PUBLIC_ACCESS }  # Ver trabajadores es público
        - { path: ^/api/proyectos, methods: [GET], roles: PUBLIC_ACCESS }    # Ver proyectos es público
        - { path: ^/api/valoracion_proyectos, methods: [GET], roles: PUBLIC_ACCESS } # Ver valoraciones es público
        - { path: ^/api/admin, roles: ROLE_ADMIN }  # Solo admins
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY } # Descomenta esto al final para proteger todo